### ISSUE TITLE
[core-upgrade] Integrate all relevant PRs from ZencashOfficial/zen into the latest release of zcash/zcash

### ISSUE THREAD

**Issue by codeparticle** [ZencashOfficial/zen#1]
Iterate through all the PRs from zencashio/zen and ZenCashOfficial/zen and integrate what is relevant into the latest release of zcash. The final result should be an upgraded zen codebase with the latest upgrades from zcash. Also all code that is ZenCash-specific will be delimited as follow:
// ZEN_MOD_START or # ZEN_MOD_START
{modified_code}
// ZEN_MOD_END or # ZEN_MOD_END

This will help pinpoint ZenCash specific code when onboarding new developers, when merging the latest code from zcash or when debugging a ZenCash-specific issue.

**Comment by tarrenj** [comment]
@FranckDG and @codeparticle  Can we close this issue now?

**Comment by tarrenj** [comment]
@albertog78 Can we close this issue now?
